### ISSUE TITLE
Add method errors in action class

### ISSUE THREAD

**Issue by marcoT89** [lorisleiva/laravel-actions#10]
First of all congratulations for the awesome package! It's very useful!

I would like to suggest adding an `errors()` method in Action class. Some times we would like to manipulate validation errors manually instead of throw a `ValidationException`.

For example:
```php
public function errors(): MessageBag
{
    return $this->getValidatorInstance()->errors();
}
```
I've created a child Action class that extends from yours and added this method. It worked just fine.
With this method we could do something like this:

```php
$action = new MyAction(['someting' => 'invalid']);

if ($action->errors()->any()) {
    $user->notify(new VeryBadErrorOccurred($action));

    throw new MyCustomException($action->errors()->messages());
}
```

What do you think? Do you think this is something simple and nice to implement? I would appreciate it.

Thank you!

**Comment by lorisleiva** [comment]
Hi there 👋 

Thanks for the kind words and the suggestion.

At the moment there is a [`failedValidation` method](https://github.com/lorisleiva/laravel-actions/blob/7f12cd6d948a971a24e2a4763bb026989d97df59/src/Concerns/ResolvesValidation.php#L98-L103) which allows you to customize the logic of failed validation.

However, this method does not really allow you to return the error bag instead of throwing an error since its a protected method (for configuration purposes only).

I like your implementation but I'd rather separate the "failed validation" logic and the "validation error bag" getter. Thus, we would have an `errors` (or maybe `validationErrors`) public method that does exactly what you've implemented, available at all time. And if an action wanted to not throw an exception and use that instead it would just need to override the `failedValidation` method.

What do you think?

**Comment by marcoT89** [comment]
Yes, I think there is no problem on the method name. I thought on `errors` name just to be simpler, but I could be `validationErrors` and it still make sense for the name. Actually it's more clear. Also it would be nice to have a public method like: `failedValidation` that returns a boolean instead of throwing an Exception. But it's ok if that's not possible.

It would be awesome to have this possibility:
```php
$action = new MyAction(['params' => 'my params']);
if ($action->failedValidation()) {
    user()->notify(new YouShouldCompleteParams($action));

    throw new IncompleteErrors($action->validationErrors()->messages());
    // or
    throw new IncompleteErrors($action->errors()->messages());
}
```

IMHO I think we should have a public method to check if validation errors have failed by default with the package rather than need to override the `failedValidation` method. It could be another public method name though. Example: `hasValidationErrors()`.

In the end, the most important feature for me is the getter for the errors bag. We can do anything with it with many possibilities.

**Comment by lorisleiva** [comment]
Hi there 👋 

This is already possible. For documentation purposes let me list some helpful methods/properties that you can use:

```php
// Returns true if validation was successful, false otherwise.
$this->passesValidation();

// Automatically called when validation fails.
// Defaults to throwing a ValidationException.
// Override to change that behaviour.
$this->failedValidation();

// Returns the validator instance. Use to access the errors.
$this->getValidatorInstance();
$this->getValidatorInstance()->errors();

// You can also access the validator like this.
$this->validator;
$this->validator->errors();
```

With all those references in mind, you can implement your action like this:

```php
class MyAction extends Action
{
    public function rules() {/* ... */}

    public function failedValidation()
    {
        // Fail silently.
    }

    public function handle()
    {
        if ($this->passesValidation()) {
            $this->user()->notify(new YouShouldCompleteParams($this));
            throw new IncompleteErrors($this->validator->errors());
        }

        // ...
    }
}
```

Now, if you want to access these methods outside the `Action` class, only the `passesValidation` method is `public`. The rest is `protected`.

I hope this helps.

**Comment by lorisleiva** [comment]
Are there any changes that you feel would make this process easier or should I just close this issue?

**Comment by marcoT89** [comment]
Sorry for the late response. 
Well... I understand all this possibilities that already have, but in my opinion, I still think it would be very nice to have the message bag available outside the action with a public method like I've mentioned above.

I personally don't like the approach to override every action to change the default behavior of a method or to do what I did, which was create a child class that provided this `errors` public method to access the message bag.

My point is, why not accessing the message bag outside the action? Is there any problem with that? Please let me know, maybe I'm just not seeing the problem.

Thank you!

**Comment by lorisleiva** [comment]
Hi there,

I'm thinking of making these adjustments today so that they are ready for 6.0.

```php
// This will be public.
$this->getValidatorInstance();

// This ...
$this->getValidationErrors();
// ... will be a shortcut method for:
$this->getValidatorInstance()->errors();
```

Would that be useful for your actions?

Is there anything else you'd like me to consider adding?

**Comment by marcoT89** [comment]
Not now! Thats enough! Thank you so much! 😉 👍

**Comment by lorisleiva** [comment]
Okay done. ✅ 

I just need to check a few more things with the `middleware` method for jobs in 6.x and I'll tag a new release.
