### ISSUE TITLE
Idea: chaining with then()

### ISSUE THREAD

**Issue by cyrillkalita** [lorisleiva/laravel-actions#101]
@lorisleiva I am sure this is possible _in theory_, and this is totally unrelated to the awesome package (shout out for 2.1!) and feel free to close it immediately, but wouldn't it be fun to be able to do something like this in Livewire and elsewhere if the `run()` was successful?:

```php
CreatePhone::run($attributes)->then(fn(Phone $phone) => $this->emit('phonesUpdated', [$phone]));
```
Is this a bad idea in general? is this breaking the SRP?

**Comment by lorisleiva** [comment]
Hi Cyrill 👋

That’s not a bad idea but that’s definitely something that would be out of scope for Laravel Actions.

I think what you’re looking for is actions as pipeline items and you definitely don’t need Laravel Actions for that. Pipeline items are usually implemented for one specific type of Pipeline and thus creating some sort of generic `AsPipelineItem` trait wouldn’t work so well.

It’s true though that there isn’t much documentation out there on the Pipeline component of the Laravel framework so maybe I should write about it in my blog.

I’ll add it to my article backlog and I’ll be sure to notify you here if I do publish it. ☺️
