### ISSUE TITLE
Error when running tests/phpunit after adding Action to $commands array in Console\Kernel.php

### ISSUE THREAD

**Issue by Robhult** [lorisleiva/laravel-actions#108]
I'm getting the error 
```
Error in bootstrap script: TypeError:
Argument 1 passed to Illuminate\Console\Application::add() must be an instance of Symfony\Component\Console\Command\Command, instance of App\Actions\ResetPasswordAction given, called in C:\Projects\www\mystangen\vendor\laravel\framework\src\Illuminate\Console\Application.php on line 260
``` 
when running tests. 
It's only happening when i'm running the tests, it works as intended when the command is run from console.

I have added the Action to the $commands property in App\Console\Kernel.php. Which makes it fail when running any test. 

PHP-version: 7.4.6.
PHPUnit-version: 9.5.4

Code from relevant files:
```php
<?php

// App\Actions\ResetPasswordAction.php

namespace App\Actions;

use App\Models\User;
use Illuminate\Console\Command;
use Lorisleiva\Actions\Concerns\AsAction;
use Password;

class ResetPasswordAction
{
    use AsAction;

    public string $commandSignature = 'user:reset-password {users*}';
    public string $commandDescription = 'Reset password of the given users.';
    public string $commandHelp = 'Reset password of the given users, by id.';

    public function handle(User $user)
    {
        //
    }

    public function asCommand(Command $command): void
    {
        // 
    }
}
```

```php
<?php

// App\Console\Kernel.php

namespace App\Console;

use App\Actions\ResetPasswordAction;
use Illuminate\Console\Scheduling\Schedule;
use Illuminate\Foundation\Console\Kernel as ConsoleKernel;

class Kernel extends ConsoleKernel
{

    /**
     * The Artisan commands provided by your application.
     *
     * @var array
     */
    protected $commands = [
        ResetPasswordAction::class,
    ];

    /**
     * Define the application's command schedule.
     *
     * @param  Schedule  $schedule
     *
     * @return void
     */
    protected function schedule(Schedule $schedule)
    {
        //
    }

    /**
     * Register the commands for the application.
     *
     * @return void
     */
    protected function commands()
    {
        $this->load(__DIR__.'/Commands');

        require base_path('routes/console.php');
    }
}

```

**Comment by lorisleiva** [comment]
Hi there 👋 

Well spotted, I think this is a bug related to the Action Manager not recognising the command pattern in tests. It should be easy to fix though. Could you just show me how you're calling the command in your tests?

**Comment by Robhult** [comment]
Hello,

The error appears even when i'm not calling the Action via any tests. It appears directly when i'm adding it to the $commands array in Kernel.php. 

Thanks for your work with this project, really like it so far. :)

Code from test below, (even when commented the error appears).
```
/** @test */
    public function it_notifies_the_user_with_a_mail_for_resetting_password()
    {
        ResetPasswordAction::run($this->user);

        Notification::assertSentTo(
            new AnonymousNotifiable,
            UserResetPasswordRequested::class
        );
    }
```

**Comment by lorisleiva** [comment]
Thank you for the extra information. I've tried to reproduce this with a fresh Laravel install but I couldn't.

Steps I followed:
- Run `laravel new debug-la-108`
- Add a `App\Actions\ResetPasswordAction` action.
- Add the action to the console `Kernel` under the `$commands` array.
- Run a test that includes `ResetPasswordAction::run();`.
- [You can find the repository here](https://github.com/lorisleiva/debug-la-108).

Would you mind helping me reproduce this issue? Thanks again for reporting this.

**Comment by Robhult** [comment]
It works as intended with your repository, might be some of my other libraries that i'm using. Or even that I have upgraded Laravel several times, the base project is from version 5.5 or 6. It's now at version 8.22.1

Will test some more.

**Comment by Robhult** [comment]
What i've tried so far:
- Adding all dependencies from my project into your.
- Changing TestCase for Test to the one from PHPUnit instead of the one with some additions in my project. 
- Updating all Kernel and Provider files to the same as your repository.
- Updating phpunit.xml to the same as yours, which was where i found the error.

### phpunit.xml
Code from my project:
```
<server name="APP_ENV" value="testing"/>
    <server name="BCRYPT_ROUNDS" value="4"/>
    <server name="CACHE_DRIVER" value="array"/>
    <server name="MAIL_DRIVER" value="array"/>
    <server name="QUEUE_CONNECTION" value="sync"/>
    <server name="SESSION_DRIVER" value="array"/>
    <server name="DB_CONNECTION" value="sqlite"/>
    <server name="DB_DATABASE" value=":memory:"/>
    <server name="APP_CONFIG_CACHE" value="bootstrap/cache/config.phpunit.php"/>
    <server name="APP_SERVICES_CACHE" value="bootstrap/cache/services.phpunit.php"/>
    <server name="APP_PACKAGES_CACHE" value="bootstrap/cache/packages.phpunit.php"/>
    <server name="APP_ROUTES_CACHE" value="bootstrap/cache/routes.phpunit.php"/>
    <server name="APP_EVENTS_CACHE" value="bootstrap/cache/events.phpunit.php"/>
```

Compared to the code from your repo:
```
<server name="APP_ENV" value="testing"/>
    <server name="BCRYPT_ROUNDS" value="4"/>
    <server name="CACHE_DRIVER" value="array"/>
    <!-- <server name="DB_CONNECTION" value="sqlite"/> -->
    <!-- <server name="DB_DATABASE" value=":memory:"/> -->
    <server name="MAIL_MAILER" value="array"/>
    <server name="QUEUE_CONNECTION" value="sync"/>
    <server name="SESSION_DRIVER" value="array"/>
    <server name="TELESCOPE_ENABLED" value="false"/>
```

It works when i remove the row:
```
<server name="APP_PACKAGES_CACHE" value="bootstrap/cache/packages.phpunit.php"/>
```

**Comment by Robhult** [comment]
Closing the issue since it's solved, see comment before this one.

**Comment by lorisleiva** [comment]
Oh wow, thanks for debugging this. I’m sure it’ll help others that are in the same situation. 🙇‍♂️

**Comment by Robhult** [comment]
Yea, hope so.

Thanks again for your work with both this and laravel-deployer projects.
