### ISSUE TITLE
Releasing a job back into the queue

### ISSUE THREAD

**Issue by BoyeMagnus** [lorisleiva/laravel-actions#109]
When handling an action as a job is it then possible to manually release it back onto the queue?
Normally in Laravel jobs you're able to run `$this->release(10);` inside of the handle function to release the current job back onto the queue.
More about Manually releasing a job:
https://laravel.com/docs/8.x/queues#manually-releasing-a-job

I've tried to implement InteractsWithQueue and Queueable. However I don't seem to be able to reach the actual job instance.

I can't seem to find anything about this functionality in the docs either

**Comment by lorisleiva** [comment]
Hi there 👋 

Laravel action will provide the `Batch` instance or the `JobDecorator` instance if they are type-hinted properly as the first argument of the `asJob` method.

See the relevant section of the documentation here: https://laravelactions.com/2.x/dispatch-jobs.html#batching-jobs.
