### ISSUE TITLE
Form Display and Update

### ISSUE THREAD

**Issue by keyurshah** [lorisleiva/laravel-actions#110]
Hello,

This package looks great! Thank you for your hard work.

In many of my use cases, I have a form that shows a button to execute an action, i.e. SyncInventory

So, it seems I would need 2 actions, one to display the form, and one to execute the action. 

Instead of creating 2 separate actions, is there a simpler way to create this pattern inside one single action?

- show form - show a view that has the base form, perhaps a dedicated function that can be used as a GET, `asForm()` ? 
- execute form on POST - call `asController()` - (current functionality)

Thank You

**Comment by lorisleiva** [comment]
Hi there 👋 

It’s a good point actually. I usually use two actions: one for displaying the form and one for handling it because I like my actions to be that granular.

However, I think there’s a way to do it in one action. I haven’t tested this but if you give a different method when defining the route it should use that one instead. For example:

```php
Route::get('MyAction@asForm');
```

Let me know if that works for you, otherwise I’m sure we can work something out. 😊

**Comment by keyurshah** [comment]
Appreciate your help!

I tried to do it 2 different ways, but it goes straight to the `handle()` method. 

```
Route::get('/test1', '\App\Actions\UploadInventory@asForm');
Route::get('/test2', [\App\Actions\UploadInventory::class,'asForm']);
```

my action looks like this

```

   public function asForm() {
        dd('inside asForm');
   }

   public function handle() {
       dd('inside handle')
   }
```

separately, in your current what naming pattern would you currently use for the form showing this button? Since it's not a true action, it seems challenging to name it as an action.

**Comment by lorisleiva** [comment]
Oh okay thanks for letting me know. I’ll have a look at how I can update the ControllerDecorator to use that information.

It usually depends on the form but I tend to prefix them with “Show” so it’s quite explicit. For example, I might have “UpdateUserProfileAction” and “UpdateUserPasswordAction” as form handlers, and then “ShowUserSettingsAction” as the action that displays both forms in the same page.

**Comment by lorisleiva** [comment]
Hi there 👋 

Sorry for the delay but, from [`v2.1.3`](https://github.com/lorisleiva/laravel-actions/releases/tag/v2.1.3), you should now be able to provide explicit methods to your route and they will be called within your action (see #123). 🙂

**Comment by keyurshah** [comment]
Sorry I missed this earlier. It looks perfect and I'll try this out. Thank you so much for putting in the time for this request!
