### ISSUE TITLE
How to arrange routes.

### ISSUE THREAD

**Issue by dluague** [lorisleiva/laravel-actions#111]
I have two action classes.

##### ShowCustomer.php
```php
public static function routes(Router $router)
{
    $router->get('customers/{customer}', static::class);
}
```

##### CreateCustomer.php
```php
public static function routes(Router $router)
{
    $router->get('customers/create', static::class);
}
```

When I access `customers/create` it thows a `No query results for model [App\Models\Customer] create` because in the route list the show route is listed first.

Thanks for this package btw.

**Comment by dluague** [comment]
I think the only solution for now is to be more specific.
```php
public static function routes(Router $router)
{
    $router->get('customers/{customer}/show', static::class);
}
```

**Comment by lorisleiva** [comment]
Hi there 👋 

Sorry for the delay, yes that's definitely an important drawback from setting your routes directly in the action since they will be registered in the order in which the files are discovered which would be alphabetically from your class names.
