### ISSUE TITLE
Uninstalling Deletes Laravel Jetstream Actions

### ISSUE THREAD

**Issue by gdconnect** [lorisleiva/laravel-actions#113]

**Comment by Wulfheart** [comment]
What exactly do you mean?

**Comment by gdconnect** [comment]
Deletes all contents of the /Actions folder.. including Jetstream and
Fortify Actions . upon uninstall

**Comment by Wulfheart** [comment]
And how do you uninstall it? Is there a special command?

**Comment by gdconnect** [comment]
composer remove lorisleiva/laravel-actions

Not aware of special command for uninstalling

**Comment by Wulfheart** [comment]
I cannot reproduce this issue. Please provide more specific information with information about your system.
Here a snippet for you to copy-paste:
```markdown
### System (please complete the following information):
 - OS: [e.g. macOS, Manjaro Linux, Windows 10]
 - PHP Version: [e.g. 8.0.3]
 - composer Version: [e.g. 2.0.0]
 - Package Version from the lock-file: [e.g. 0.2.2]
 - Laravel Version from the lock-file: [e.g. 8.5.2]
 - Shell: [e.g. Powershell, cmd, bash, zsh]
 ```

## My Reproduction try

### System:
 - OS: Manjaro Linux
 - PHP Version: 8.0.6
 - composer Version: 2.0.13
 - Package Version from the lock-file: 2.1.2
 - Laravel Version from the lock-file: 8.43
 - Shell: bash

## #Reproduction script for bash
`composer create-project laravel/laravel issue -q && cd issue && composer require laravel/jetstream lorisleiva/laravel-actions -q && php artisan jetstream:install livewire -q && php artisan make:action TestAction -q && composer remove lorisleiva/laravel-actions -q && printf "\nContents of the app/Actions Folder\n\n" && ls -lac ./app/Actions`

### Result

As expected:
```
Contents of the app/Actions Folder

total 20
drwxr-xr-x 4 alexw alexw 4096 May 27 12:05 .
drwxr-xr-x 9 alexw alexw 4096 May 27 12:05 ..
drwxr-xr-x 2 alexw alexw 4096 May 27 12:05 Fortify
drwxr-xr-x 2 alexw alexw 4096 May 27 12:05 Jetstream
-rw-r--r-- 1 alexw alexw  170 May 27 12:05 TestAction.php
```

**Comment by lorisleiva** [comment]
Hi there 👋 

Thanks Alex for looking into this. I'm going to close this due to inactivity and lack of information but feel free to open a new issue with a more detailed description of the issue and how to reproduce it so we can fix it.
