### ISSUE TITLE
Conflict: must be an instance of Illuminate\Events\Dispatcher, instance of LorisLeiva\Actions\EventDispatcherDecorator

### ISSUE THREAD

**Issue by affektde** [lorisleiva/laravel-actions#12]
In combination with https://github.com/musonza/chat after update to v0.1.3 this exception is thrown. Seems to be like a conflict with the new pushed decorator?

How could you configure or fix this class problem?

```Argument 1 passed to Musonza\Chat\Eventing\EventDispatcher::__construct() must be an instance of Illuminate\Events\Dispatcher, instance of LorisLeiva\Actions\EventDispatcherDecorator given {"userId":298,"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Argument 1 passed to Musonza\\Chat\\Eventing\\EventDispatcher::__construct() must be an instance of Illuminate\\Events\\Dispatcher, instance of LorisLeiva\\Actions\\EventDispatcherDecorator given at /data/www/vendor/musonza/chat/src/Eventing/EventDispatcher.php:12)```

**Comment by musonza** [comment]
This is not not a problem with `lorisleiva/laravel-actions`. I should use a contract instead of of the concrete class. I will fix in https://github.com/musonza/chat so you can can close this here and open an issue there if you need.

**Comment by musonza** [comment]
I have created a release for https://github.com/musonza/chat/releases/tag/v3.3.2 so please close this when you get a chance @affektde

**Comment by affektde** [comment]
Wow super @musonza You are awesome! Thank you for your awareness! Much love from Munich.

**Comment by lorisleiva** [comment]
That's amazing, thanks for your reactivity @musonza!
