### ISSUE TITLE
Actions not being invoked

### ISSUE THREAD

**Issue by iamlasse** [lorisleiva/laravel-actions#128]
Hi I get this when I follow the tutorials.

Invalid route action: [App\Http\Controllers\GetUserProfile]

App\Http\Controllers\GetUserProfile` was not found: Controller class `App\Http\Controllers\GetUserProfile` for one of your routes was not found. Are you sure this controller exists and is imported correctly?

It seems the namespace clashes and the default search route is overriding the action class I've used in web.php route config.

`Route::get('users/{user}', GetUserProfile::class);`

Any suggestions?

**Comment by lorisleiva** [comment]
Hi there 👋 

Try `Route::get('users/{user}', '\\' . GetUserProfile::class);`.

Alternatively, you can remove the namespace prefix from your `RouteServiceProvider` but you'll have to use the `::class` notation for your other existing routes.

**Comment by iamlasse** [comment]
Hi Thank you, I added a route file and removed the namespace for that one to handle actions. Might be a good idea to add that in the docs, it took me a while to figure that one out lol I noticed it was in the doc for v.1 but not v2.
