### ISSUE TITLE
How to create progress bar in command?

### ISSUE THREAD

**Issue by abrampl** [lorisleiva/laravel-actions#131]

**Comment by Wulfheart** [comment]
I think it should be something like `$this->output->...` or `$this->command->...` and then the rest from the Laravel docs. 
Could you please verify if that works and write it here? If it doesn't work please also post your code.

**Comment by lorisleiva** [comment]
Hi there 👋 

Just like you would in a `Command` class but instead of using `$this` you need to use `$command` to access it.

```php
use Illuminate\Console\Command;

class ExportUserData
{
    use AsAction;

    public string $commandSignature = 'export:user';

    public function asCommand(Command $command): void
    {
        $bar = $command->getOutput()->createProgressBar(42);
        $bar->start();
        $bar->advance();
        $bar->finish();
    }
}
```

**Comment by Wulfheart** [comment]
Ah ok. I got this wrong I think. However, with this answer I think this issue can be clossed.
