### ISSUE TITLE
[Octane] Event use handle instead of asListener

### ISSUE THREAD

**Issue by exodusanto** [lorisleiva/laravel-actions#136]
Using Laravel Octane seems that actions are run as object instead of listener.

The problem is similar to #87, the workaround on EventServiceProvider event/listener registration works.

`UserUpdated::class => NotifyUserUpdated::class.'@asListener'`

**Comment by lorisleiva** [comment]
Hi there 👋 

Thanks for raising this! The issue with #87 was that Laravel Actions was not able to recognise the action as being a listener due to [a lack of recognised frames](https://github.com/lorisleiva/laravel-actions/commit/6e3c645dba54cc99b93d9a7c2417ef74b6875f2c#diff-ded0fad25fde19efbf4d7c0ed09f7924c462bd2ffd385e476a4e5b54683db46aR20-R23).

Since I've not used Octane yet, would you be able to tell me how Laravel dispatches listeners when used with Octane? It could be using a different method or perhaps even a different class than the ones listed above which would cause Laravel Actions to default to returning an object.

**Comment by exodusanto** [comment]
This is a trance of the exception.

```
#0 /.../vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(424): App\\Actions\\User\\SetupCompleted->handle(Object(App\\Events\\UserUpdated))
#1 /.../vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(249): Illuminate\\Events\\Dispatcher->Illuminate\\Events\\{closure}('App\\\\Events\\\\User...', Array)
```

**Comment by lorisleiva** [comment]
Hey 👋  Sorry for the late reply. I finally got around to checking it out. Could you try to use `dev-main` and let me know if that fixes your issue?

**Comment by exodusanto** [comment]
Hi, thank you for your fix, but it doesn't work.

I have the same exception: 
```
App\Actions\User\SetupCompleted::handle(): Argument #1 ($user) must be of type App\Models\User, App\Events\UserUpdated given, called in /.../vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php on line 424
```

I also made some tests but I'm worried that `beforeResolving` is not supported from Octane, or for integrate it this package need to register some logic into `octane.php` file

```php
 RequestReceived::class => [
            ...Octane::prepareApplicationForNextOperation(),
            ...Octane::prepareApplicationForNextRequest(),
            //
        ],
```

**Comment by lorisleiva** [comment]
No worries, thanks for trying!

If anyone using Octane would like to open a PR for this, that would be most appreciated. ❤️

**Comment by exodusanto** [comment]
Maybe @nunomaduro can give us a hit if nowadays Octane support `beforeResolving` in some way

**Comment by nunomaduro** [comment]
Are you able to make a pull request in Octane with a failing test? Or create an issue, with a repository example, so I can reproduce the issue locally?

**Comment by exodusanto** [comment]
Hi Nuno!

This is the [repo](https://github.com/exodusanto/laravel-actions-octane-repro).

To setup the reproduction DB
```bash
php artisan migrate:fresh
php artisan db:seed # this will create an user
```

There are two commits:
1. __Base reproduction__
2. __Octane installed__

### Base reproduction
Route `/` send and event `UserUpdated` and the listener action `UserUpdateTask` writes on logs a message.

### Octane installed
Starting the server with Octane the same flow throws the error

**Comment by Wulfheart** [comment]
@exodusanto I think he meant that you should create an issue in the Octane repo itself.

**Comment by binaryfire** [comment]
Hi all

Has anyone found a solution for this? I’m keen to try a fully actions-based architecture for a new project but we’re using Octane.

Nuno mentioned Octane supports `beforeResolving` so that doesn’t seem to be the problem: https://github.com/laravel/octane/issues/542

**Comment by exodusanto** [comment]
Not yet 😔, I'll find some times next weeks
