### ISSUE TITLE
Guest user policy in authorize function of action

### ISSUE THREAD

**Issue by Celant** [lorisleiva/laravel-actions#137]
Hey, love the package 🙂

Is there any guidance on how to correctly check a policy that has a [nullable user argument](https://laravel.com/docs/8.x/authorization#guest-users)? 
My policy check has a nullable user argument, but I can't call it within the authorize function of my Action.

Usually you'd call a policy check something like:
```php
public function authorize(ActionRequest $request, Event $event): bool
{
    return $request->user()->can('view', $event);
}
```
but if the request is not authenticated, the user returns nil resulting in a `Call to a member function can() on null` exception.

Another way suggested by laravel would be to use the controller helper:
```php
public function authorize(ActionRequest $request, Event $event): bool
{
    $this->authorize('view', $event);
}
```
but this also doesn't work, as the Action is not a Controller.

Are there any suggestions on how to call a policy function that takes a nullable user from within an Action?

**Comment by Celant** [comment]
Thanks for the super quick reply! I think that solves my issue, but there might be a secondary one.

In every case I've tested in my application, the `$event` parameter passed to the `authorize` function is always null. If I check the parameter in the `handle` function, it is correctly present. Just not in the `authorize` function!

Full code sample is below, and I am truly puzzled 🙂 
```php
class ShowEvent
{
    use AsAction;

    public function authorize(ActionRequest $request, Event $event): bool
    {
        dd($event->id);
        return Gate::check('view', $event);
    }

    public function handle(ActionRequest $request, Event $event): Response
    {
        return Inertia::render('Events/Show', [
            'event' => $event,
        ]);
    }

    public function asController(ActionRequest $request, Event $event): Response
    {
        return $this->handle($request, $event);
    }
}
```
In this case, `dd` just shows null.

**Comment by Celant** [comment]
@lorisleiva I suspect the issue here is that `inspectAuthorization()` in the ValidateActions concern uses `$this->resolveAndCallMethod('authorize')`, whereas the ControllerDecorator uses `$this->resolveFromRouteAndCall()`.

The former uses the service container to resolve dependencies and then call the method, whereas the latter does the same but also includes `$this->route->parametersWithoutNulls()`, meaning handle gets the Event object from the route correctly but authorize doesn't.

I don't know enough about Laravel and this library to know whether it's as simple as just including the parametersWithoutNulls in the arguments passed to `resolveAndCallMethod`, or if some wider change is needed to support this.

If it is the former, I am happy to try and PR that. Otherwise, I'll need your help on this one.
Additionally, It looks like the tests cover controllers with implicit route bindings, as well as authorization and validation, but _not_ both. Maybe this is an edge case that requires a test case? 🙂

**Comment by lorisleiva** [comment]
I've moved this conversation to #140.
