### ISSUE TITLE
Importing actions from packages

### ISSUE THREAD

**Issue by usernotnull** [lorisleiva/laravel-actions#143]
Actions::registerCommands & Actions::registerRoutes fail to import packages in vendor directory.

This is because `vendor/lorisleiva/laravel-actions/src/Util.php::getClassnameFromRealpath` 's assumption for class names breaks the way it is coded when dealing with scenarios where the namespace doesn't start with app but src, as common in packages.

Any plans to work on this issue from your side? I would submit a PR but it'll take a while cuz I'm swamped. I extracted some actions to a package in order to share it with multiple projects and found this issue.

**Comment by lorisleiva** [comment]
This has been implemented in the [Lody package](https://github.com/lorisleiva/lody) which is now being used by Laravel Actions to register routes and commands. This means Laravel Actions now supports registering routes and commands in any namespace — not only in the `App` namespace — and even in any namespace within your `vendor` directory. It uses your `vendor/composer/autoload_psr4.php` file which uses the PSR-4 configurations present in your `composer.json`.

This was released in [`v2.2.0`](https://github.com/lorisleiva/laravel-actions/releases/tag/v2.2.0). 🚀
