### ISSUE TITLE
Route issue when using Ziggy

### ISSUE THREAD

**Issue by raftalks** [lorisleiva/laravel-actions#149]
There seems to be a conflicting issue with this package or with [Ziggy](https://github.com/tighten/ziggy)
when using this package. 

I am using Ziggy to get the list of routes loaded to frontend react application which seems to have an issue with Actions registered in the routes. This may not be relevant to this package but thought of letting you guys know and clarify how I should work around the issue.

To recreate the issue, simply install Ziggy as per their instruction and try register an action route, you will get an exception thrown.

**Comment by lorisleiva** [comment]
Could you please describe the issue?

**Comment by raftalks** [comment]
Sorry, 

Finally figured out, the issue is not related to package.

Further checking realised it was a mistake one of the route that was registered as mentioned in the issue below

https://github.com/tighten/ziggy/issues/364
