### ISSUE TITLE
Update Readme: Spy section

### ISSUE THREAD

**Issue by usernotnull** [lorisleiva/laravel-actions#152]
Referencing: https://laravelactions.com/2.x/mock-and-test.html#spying

When a test is run, $spy is a Mockery\Expectation when allowToRun() is used. 
Mockery\Expectation does not have a method "shouldHaveReceived".

If I want to call `shouldHaveReceived`, $spy should be as below to resolve to a MockInterface instead of an Expectation:
```
$spy = SendTweet::spy();
```

**Comment by lorisleiva** [comment]
Thanks for that, I've updated the readme. 🙂
