### ISSUE TITLE
ArgumentCountError: Too few arguments to function

### ISSUE THREAD

**Issue by jonquihote** [lorisleiva/laravel-actions#155]
Hi there,

I would like to try this package and has encountered an error.

```
The following exception occurred during the request:

ArgumentCountError: Too few arguments to function
Vendor\Package\Actions\ServeRootPage::handle(), 0 passed in
/Users/jonquihote/GitHub/vendor-package-actions/vendor/lorisleiva
/laravel-actions/src/Concerns/AsController.php
on line 14 and exactly 1 expected in
/Users/jonquihote/GitHub/vendor-package-actions/src/Actions/ServeRootPage.php:13
```

I was under the impression that the dependency required by the `handle()` method will be resolved by the `Container` but it doesn't seem like it is doing so and I have no idea where to go from here.

What surprises me is that the code would work when accessed through the browser, but it didn't work when accessed from the test.

I've already set up a minimal reproducible repository as well and I hope to ask for your advice on how to solve this issue.
https://github.com/jonquihote/vendor-package-actions

Thank you very much for taking the time to read this issue.

Best regards,
Joni Chandra

**Comment by lorisleiva** [comment]
Hi there 👋

No, the handle method does not resolve its arguments from the container, the constructor of the action does.

**Comment by jonquihote** [comment]
Hi there,

Thank you very much for your response. I really appreciate it.

I see that the handle does not resolve its arguments from the container. Have you take a look at the repository I linked?
I wanted to use the `Action` as `Controller` only and I'm trying to inject `Request` object into the `handle` method but have been unable to due to the error above.

I was wondering if I'm doing it wrong if you could enlighten me.

Thank you again for your response.

Best regards,
Joni Chandra

**Comment by lorisleiva** [comment]
Hey 👋 sorry for the late reply.

For that you can use `asController` which will resolve its arguments against the route parameters just like you would in the `__invoke` method of an invokable controller.

https://laravelactions.com/2.x/register-as-controller.html#from-controller-to-action
