### ISSUE TITLE
AsJob decorator and makeJob issue

### ISSUE THREAD

**Issue by abrampl** [lorisleiva/laravel-actions#157]
When i register job with decorator like:

```php
class BookingAction implements ShouldBeUnique
{
    use AsAction;

    public function asJob(JobDecorator $job, Model $model): void {
    }
}
```

And after that i try to makeJob from this like:

```php
BookingAction::makeJob($model)
```

I see error Argument 1 ($job) must be of type Lorisleiva\Actions\Decorators\JobDecorator, App\Models\Model given

**Comment by travisaustin** [comment]
I think you need to change your `BookingAction` class to:

```
class BookingAction implements ShouldBeUnique
{
    use AsAction;

    public function asJob(Model $model): void {
    }
}
```

**Comment by abrampl** [comment]
Nope, 
i need to have access to JobDecorator like in this example to access job

https://laravelactions.com/2.x/dispatch-jobs.html#batching-jobs

**Comment by lorisleiva** [comment]
Hi there 👋

When using the `ShouldBeUnique` trait, you should type-hint the `UniqueJobDecorator` instead.

```php
class BookingAction implements ShouldBeUnique
{
    use AsAction;

    public function asJob(UniqueJobDecorator $job, Model $model): void {
    }
}
```

**Comment by lorisleiva** [comment]
That being said, type-hinting the `JobDecorator` should also work according to the code base. I'll investigate soon.

https://github.com/lorisleiva/laravel-actions/blob/277d90122dad6469b1ecfc07111e8d40f1854c25/src/Decorators/JobDecorator.php#L171

**Comment by lorisleiva** [comment]
I've created a fix for this. It should now work no matter how you type-hint the `JobDecorator`. The fix will be available in the latest version (hoping to tag today).
