### ISSUE TITLE
Laravel 9 support

### ISSUE THREAD

**Issue by davidjr82** [lorisleiva/laravel-actions#165]
Hi! Do you have planned to support Laravel 9? It would be great.

Thanks!

**Comment by lorisleiva** [comment]
Hey 👋 

It's already done but I just need to test it manually before releasing the version. If you can try it using `dev-main` as well, that'd be super helpful.

**Comment by davidjr82** [comment]
Sure, it will take me some days but as soon as I can do it, I will give you feedback. Have a nice weekend!

**Comment by davidjr82** [comment]
Hi!

Couldn't install it in a fresh Laravel 9 installation:

Steps:
- `laravel new l9-dev --dev`
- `php artisan --version` displays `Laravel Framework 9.x-dev`
- `composer require lorisleiva/laravel-actions:dev-main` throws the next error:

`
Problem 1
    - Root composer.json requires lorisleiva/laravel-actions dev-main -> satisfiable by lorisleiva/laravel-actions[dev-main].
    - lorisleiva/laravel-actions dev-main requires illuminate/contracts ^8.15|9.x-dev -> found illuminate/contracts[v8.15.0, ..., 8.x-dev, 9.x-dev] but these were not loaded, likely because it conflicts with another require. 
`

**Comment by davidjr82** [comment]
Honestly, the official release date is in 8 days, so I guess you can wait until then to solve the issue and don't waste time.

It's up to you, but if I were you, I would close the issue 🗡️ 

Have a nice week!

**Comment by lorisleiva** [comment]
Haha, thanks. I'll wait until Wednesday because `beta-5` should be released by now and hopefully that will solve this issue. 🤞

**Comment by lorisleiva** [comment]
As predicted, using `beta-5` released yesterday fixed the issue. 🥳 

After installing a fresh Laravel app, you can run:

```shell
composer require lorisleiva/laravel-actions:2.3.0-beta.2
```

Thanks again for raising this!
