### ISSUE TITLE
Route resource redirecting to home

### ISSUE THREAD

**Issue by rafa-acioly** [lorisleiva/laravel-actions#169]
After registering my action in my routes:

```php
Route::prefix('products')->group(function () {
    Route::put('/', UpsertProduct::class);
    Route::get('/', function () {
        return "ok";
    });
});
```

The `PUT` endpoint always redirect to the home page.
I've added the method `asController` like this:

```php
public function asController(Request $request): JsonResponse
{
    return response()->json(["ok"]);
}
```

What am I missing? The package version works on Laravel 9?

### Details:

```json
{
    "php": "^8.0.2",
    "laravel/framework": "^9.0",
    "lorisleiva/laravel-actions": "^2.3"
}

**Comment by rafa-acioly** [comment]
I've notice that the validations was not passing and for that reason the redirect occurs.

Now, how can I send a json response with the errors that occur?

**Comment by Wulfheart** [comment]
Maybe this helps?
https://laravelactions.com/2.x/as-controller.html#jsonresponse

**Comment by Wulfheart** [comment]
@rafa-acioly Maybe send it with a header that it expects JSON?

**Comment by rafa-acioly** [comment]
adding the `Accept: application/json` header worked, thanks!
