### ISSUE TITLE
[Suggestion] Add custom messages function

### ISSUE THREAD

**Issue by phiter** [lorisleiva/laravel-actions#17]
I had a situation where I needed to set custom messages for my validations, and I wish there was an easier way to set them (even though the way I did it was pretty easy).

This is what I did:

    public function rules()
    {
        return [
            'name' => 'required|unique:subdomains,name|min:4|alpha_dash',
            'token' => 'required'
        ];
    }

    public function withValidator($validator)
    {
        $validator->setCustomMessages([
            'name.unique' => 'This subdomain already exists.',
        ]);
    }

This is what I would propose:

    public function rules()
    {
        return [
            'name' => 'required|unique:subdomains,name|min:4|alpha_dash',
            'token' => 'required'
        ];
    }

    public function customMessages()
    {
        return [
            'name.unique' => 'This subdomain already exists.',
        ];
    }

**Comment by lorisleiva** [comment]
Hi there 👋 

That actually already exists. The `message` and `attribute` methods are available ([see source](https://github.com/lorisleiva/laravel-actions/blob/e201a841d40d0af4349a01b447b36cc4751e949c/src/Concerns/ResolvesValidation.php#L44-L52)).

```php
class MyAction
{
    public function rules()
    {
        return [];
    }

    public function messages()
    {
        return [];
    }

    public function attributes()
    {
        return [];
    }
}
```

I should probably update the documentation to include this. I'll leave this open until then.

Thanks for opening this issue. 👍

**Comment by phiter** [comment]
Ahhh it already exists, my bad then. Updating the docs will be helpful.

Thanks for the quick reply!

**Comment by lorisleiva** [comment]
Documentation updated ✅
