### ISSUE TITLE
Example Projects

### ISSUE THREAD

**Issue by Wulfheart** [lorisleiva/laravel-actions#171]
Hello, 

I am currently working on a new version of the Laravel Actions IDE Helper and I was wondering if there are well known open source projects using Actions. This would be beneficial as I could use some real world classes to test the output of the IDE Helpers.

Thanks in advance.

**Comment by lorisleiva** [comment]
That's a good question! The only significant OSS project I can see from the dependent list is [Candy API](https://github.com/getcandy/candy-api) but they seem to still be using v1.
