### ISSUE TITLE
CreatesMatchingTest not found

### ISSUE THREAD

**Issue by soipo** [lorisleiva/laravel-actions#177]
Hi there,
it seems like the CreatesMatchingTest has been removed, I am unable to update my dependencies.

`Trait "Illuminate\Console\Concerns\CreatesMatchingTest" not found

  at vendor/lorisleiva/laravel-actions/src/Console/MakeActionCommand.php:8
      4▕ 
      5▕ use Illuminate\Console\Concerns\CreatesMatchingTest;
      6▕ use Illuminate\Console\GeneratorCommand;
      7▕ 
  ➜   8▕ class MakeActionCommand extends GeneratorCommand
      9▕ {
     10▕     use CreatesMatchingTest;
     11▕ 
     12▕     protected $name = 'make:action';
`

Any suggestion ? Perhaps using  CallsCommands in stead ?

**Comment by soipo** [comment]
https://github.com/lorisleiva/laravel-actions/compare/main...soipo:patch-1

**Comment by renepardon** [comment]
Same problem here.. using version 2.4.0

**Comment by lorisleiva** [comment]
Hi there 👋 

Is this still an issue? If so, could you please open a PR? 🙏

**Comment by renepardon** [comment]
> main...soipo:patch-1

@lorisleiva doesn’t this one fix it?
