### ISSUE TITLE
How to catch exceptions in handle methods

### ISSUE THREAD

**Issue by kai0310** [lorisleiva/laravel-actions#178]
Hey there 👋 Thanks for the great package.

I present here as an example a program that throws an error in a handle method and catches this error and displays it in a modal. This is the smallest example that presents this problem.

## Minimum code ✍️
```PHP
class CreateOrder
{
    use AsAction;

    /**
     * @throws CannotOrderItemException
     */
    public function handle(Item $item): Order
    {
        $unpaid = Auth::user()?->orders()->delivered()->notPaid()->count();

        if ($unpaid >= Order::MAX_ORDER) {
            return throw CannotOrderItemException::hasUnpaid();
        }
        
        // and create Order Object.....  
    }
}
```

```PHP
try {
    $order = CreateOrder::run($this->item);
} catch (CannotOrderItemException $e) {
    // show error modal
}
```
## What's at stake 🤧
The IDE will tell me that a `CannotOrderItemException` is never thrown within a `try`.
This may be because execution is done only once via the run method. However, since it is not an independent run method, it is not possible to specify separately the exceptions that may be thrown.
If I write code that throws exceptions in a handle method using Laravel Actions, how is it smart to resolve these?
<img width="487" alt="スクリーンショット 2022-03-13 17 43 22" src="https://user-images.githubusercontent.com/52205108/158051932-e0db10ea-ed26-4384-bad3-0d4edff1f822.png">

**Comment by kai0310** [comment]
@lorisleiva 
Oops. I forgot to mentions it.

**Comment by travisaustin** [comment]
This requires a little extra effort, but it should work:

```php
class CreateOrder
{
    use AsAction;

    use \Lorisleiva\Actions\Concerns\AsObject {
        \Lorisleiva\Actions\Concerns\AsObject::run as parentRun;
    }

    /**
     * @see static::handle()
     * @param mixed ...$arguments
     * @return mixed
     * @throws CannotOrderItemException
     */
    public static function run(...$arguments)
    {
        return self::parentRun(...$arguments);
    }
    
    /**
     * @throws CannotOrderItemException
     */
    public function handle(Item $item): Order
    {
        $unpaid = Auth::user()?->orders()->delivered()->notPaid()->count();

        if ($unpaid >= Order::MAX_ORDER) {
            return throw CannotOrderItemException::hasUnpaid();
        }
        
        // and create Order Object.....  
    }
}

```

**Comment by kai0310** [comment]
@travisaustin 
Thanks! However, it is only a first aid kind of thing, and I don't think it is a smart thing to do.

**Comment by Wulfheart** [comment]
What about registering it as a Laravel Exception and handling it there?

**Comment by kai0310** [comment]
@Wulfheart 

Thank you very much. However, I still can't seem to figure out how to do that. What code would solve this case?

**Comment by Wulfheart** [comment]
No idea. Just a hint for you...

**Comment by jameshulse** [comment]
I think you shouldn't be throwing an exception, but instead returning a kind of 'Result' object.

**Comment by kai0310** [comment]
Ah, pretty good 👍🏻 

I was feeling that throwing it as an exception would make the code more readable, but I guess I can solve it by returning a new object like a Result object!
thanks

**Comment by kai0310** [comment]
This is not a problem with this package, but with the PHPDocument specification. As such, I am closing this issue.

It seems we need to discuss how to use the package, not how to solve the problem as a package.
