### ISSUE TITLE
assertPushed() does not seem to work with queue sync

### ISSUE THREAD

**Issue by davidjr82** [lorisleiva/laravel-actions#180]
Hi!

I have this test assertion in my tests:

```php
SendWelcomeEmail::assertPushed(function (SendWelcomeEmail $job) use ($user) {
    return ($job->user->id === $user->id) && !empty($job->new_password);
});
```

And I get this error in console when I run them:
```bash
Call to undefined method Illuminate\Queue\SyncQueue::pushed()

(...)

  1   ...\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php:337
      Illuminate\Queue\QueueManager::__call("pushed")

  2   ...\vendor\lorisleiva\laravel-actions\src\Concerns\AsJob.php:138 
      Illuminate\Support\Facades\Facade::__callStatic("pushed")
```

Of course, in my testing environment I have the queue env in sync:

phpunit.xml:
```xml
<env name="QUEUE_CONNECTION" value="sync"/>
```

Am I doing something wrong, or is it a bug on the assertion method when working with the sync queue driver and laravel actions?

Thanks!

**Comment by yugen** [comment]
Can confirm.

**Comment by leandrodiogenes** [comment]
did you have setted queue to fake before your test?
```php
Queue::fake();
```

**Comment by yugen** [comment]
> 

I did not.

**Comment by yugen** [comment]
> did you have setted queue to fake before your test?
> 
> ```
> Queue::fake();
> ```

I did not.  I was mocking the Bus (`Bus::fake()`) and but I see the distinction now. 

I can confirm that when setting up a fake queue with `Queue::fake`  `assertPushed` works even using the `sync` queue driver.

Thanks @leandrodiogenes!

**Comment by davidjr82** [comment]
I still get the same error even with `Queue::fake();`. But I assume it is something related to my code if 2 of you can make it work mocking queue instead of bus, so I will close the issue and let anyone open a new issue if this happens to them.
