### ISSUE TITLE
How to implement public $deleteWhenMissingModels = true;

### ISSUE THREAD

**Issue by diazsasak** [lorisleiva/laravel-actions#181]
Hi admin,

how to implement public $deleteWhenMissingModels = true; on an action class?

Thank you

**Comment by howdu** [comment]
I was looking for the ability to do the same. Did you find a solution? I can't find a way of doing it via the configureJob

https://laravel.com/docs/10.x/queues#ignoring-missing-models

**Comment by edwinvdpol** [comment]
Here you go: #283

**Comment by edalzell** [comment]
This can be closed cuz it's been implemented and released.
