### ISSUE TITLE
Actions as listeners are run as 'object'

### ISSUE THREAD

**Issue by mortenscheel** [lorisleiva/laravel-actions#20]
When actions are registered as event listeners, the `runAsListener()` method is never called, and the action runs as 'object'. This also means that attributes are not collected from the event.
Apparently Laravel's EventDispatcher resolves the Action and calls the `handle()` method directly.

Not sure if this is a bug, or I'm misunderstanding something.

**Comment by mortenscheel** [comment]
Fixed in #21

**Comment by lorisleiva** [comment]
#21 merged. Thanks again
