### ISSUE TITLE
Breaking change in Laravel v9.38.0 - removed methods from SerializesModels trait

### ISSUE THREAD

**Issue by careybaird** [lorisleiva/laravel-actions#207]
A fatal error occurs when dispatching jobs due to this recent change in Laravel:

https://github.com/laravel/framework/pull/44847

The JobDecorator in Laravel Actions relies on these methods.

**Comment by lorisleiva** [comment]
Thanks for raising this!

Fortunately, the fix was very simple. I've created a new patch release (See [`v2.4.2`](https://github.com/lorisleiva/laravel-actions/releases/tag/v2.4.2)).

**Comment by careybaird** [comment]
Awesome! Thank you for the super fast response 🙏
