### ISSUE TITLE
Feature Request: Force JSON responses for all actions (configurable).

### ISSUE THREAD

**Issue by patrickcurl** [lorisleiva/laravel-actions#22]
I think maybe something like 
```php
protected function allowedResponses(){
  return config('actions.response_types', ['html', 'json']);
}
```

which if the config defaults to only json for example then failedValidation would look something like: 
```php
protected function failedValidation()
    {
       ...
       if(
           count($this->allowedResponses() === 1) 
          && in_array('json', $this->allowedResponses()
       ){
            $errors = (new ValidationException($this->validator))->errors();
            throw new HttpResponseException(
                response()->json([
                        'errors' => $errors
                    ], 
                   JsonResponse::HTTP_UNPROCESSABLE_ENTITY
               )
           );
        }
       ...
```

I've implemented this myself for an API by just overwriting the failedValidation, so it doesn't redirect, and extending the Action class, but it would be neater if it was just baked into the original class.  There could be a better way of doing this as well, and there's also the option of forcing the middleware to change headers to add 'accept: application/json' but I felt that was a bit messy.

**Comment by lorisleiva** [comment]
Hi there 👋 

Thanks for the suggestion. Unfortunately, I think this is quite a particular use-case that I wouldn't be prepared to integrate by default unless it becomes a popular demand.

A few points on your solution though. I think validation should be based on the input provided to the action and not so much on the type of response that we expect to receive. Also, actions do not have to be only controllers so in some cases JSON or HTML might be completely irrelevant. I guess I struggle to understand who you are trying to protect yourself from by forcing JSON responses.

Thanks again for open this issue though. It's always nice to read how users use this package and what would make it better for them.

**Comment by patrickcurl** [comment]
It would just be nice to be able to always get only json responses by default when invoking a controller action. 

I namely use laravel for vue or mobile backends. 95% of the time I'm returning json. Being able to just default to json would be nice as I was trying essentially to login via api using curl/postman and it kept redirecting and getting a 404 error till I figured out it was because I didn't have the header: 'Accept: application/json', I'd rather have one place to configure that, so I don't have to always pass in that header. 

I mean I can set that up in axios/interceptor, but it's just more data that needs passed through the pipe, I prefer configuring as much as possible on the server instead of relying on ajax headers and what not. 

I've made it work for my use case w/ the above snippets by overriding things, I just thought maybe others would have similar issues.

**Comment by lorisleiva** [comment]
I also use Laravel Action for pure APIs most of the time and only return JSON on my actions. Nothing stops you from only returning JSON in your `response` method like so.

```php
class SearchArticles extends Action
{
    // ...
    
    public function response($articles)
    {
        return ArticleResource::collection($articles);
    }
}
```

What I don't understand is why having an option that forces yourself to return JSON?
