### ISSUE TITLE
can't update or install since package ridzhi/docbuilder is not found

### ISSUE THREAD

**Issue by romaldyminaya** [lorisleiva/laravel-actions#253]
Hi,

I'm trying to update the package but is throwing up errors since the package ridzhi/docbuilder is not found.

![image](https://github.com/lorisleiva/laravel-actions/assets/2809147/b82964b2-eca8-4de6-8b92-bffb726c1cad)

**Comment by Wulfheart** [comment]
Which version do you try to install?

**Comment by romaldyminaya** [comment]
Hi @Wulfheart ,

v2.7.0

![image](https://github.com/lorisleiva/laravel-actions/assets/2809147/9094570a-8e8d-4f1f-ba18-a3e03c64bccc)

**Comment by lorisleiva** [comment]
Hi there, I've never heard of this package before. Are you sure this is coming from Laravel Actions? If so, could you tell me the chain of dependencies that end up installing it?

**Comment by Wulfheart** [comment]
@lorisleiva I am quite sure that it is from the ide helper package. 

@romaldyminaya Could you please give me the output of `composer why ridzhi/docbuilder`?
If it is related to the Laravel Actions IDE Helper then try to upgrade it to the latest version.

**Comment by romaldyminaya** [comment]
Hi, 

Thanks @Wulfheart,

I didn't know about composer why command and it helps me find out that that package was not needed at all, I removed it from my composer.json file, and it works now.

I removed the Laravel Actions IDE Helper and composer update ran smothly.

Thanks guys for your support, Laravel Actions is a top notch package.

Love you guys.
