### ISSUE TITLE
Not working in laravel 11.21.x

### ISSUE THREAD

**Issue by FlexIDK** [lorisleiva/laravel-actions#288]
Error in [ResolvesRouteDependencies.php](https://github.com/laravel/framework/compare/v11.20.0...v11.21.0#diff-453d4a1b4e60e4a93d33f4845b551ddfd3d2d7fa0c1ab363c1f29d1adee38f6f)

Illuminate\Routing\RouteDependencyResolverTrait - deprecated

Need add $container to src/Decorators/ListenerDecorator.php

```php
<?php
...
use Illuminate\Container\Container;
...
    protected $container;

    public function __construct($action) {
        ...
        $this->container = new Container;      
    }
...
?>
```

**Comment by lorisleiva** [comment]
Hi there, thanks for raising this. Indeed I can see that the test for `latest-stable` are now failing on CI.

Would you be able to release a PR that fixes it?

**Comment by FlexIDK** [comment]
https://github.com/lorisleiva/laravel-actions/pull/289
