### ISSUE TITLE
Lorisleiva\Actions\ActionManager::identifyFromBacktrace():

### ISSUE THREAD

**Issue by hipoagencia** [lorisleiva/laravel-actions#303]
Hello!

I started to get this error message into a new project:

PHP Deprecated:  Lorisleiva\Actions\ActionManager::identifyFromBacktrace(): Implicitly marking parameter $frame as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/vendor/lorisleiva/laravel-actions/src/ActionManager.php on line 134

How can i solve it? I can't run any action as a Job.
Thanks

**Comment by hipoagencia** [comment]
Sorry.. just updated and the messages gone

**Comment by wwqwq2313** [comment]
Hello, we tried to solve the issue.

This is what we did:

Modified the identifyFromBacktrace() method signature in ActionManager.php to explicitly declare the nullable type for the $frame parameter. This resolves the deprecation warning and ensures compatibility with newer PHP versions.

You can review changes in this commit: https://github.com/wwqwq2313/lorisleiva-laravel-actions-303/commit/6dcd85c73fa4bb03f4a0ec0a49506c9601c7aecc.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

Latta AI seeks to solve problems in open source projects as part of its mission to support developers around the world. Learn more about our mission at https://latta.ai/ourmission . If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
