### ISSUE TITLE
How to inject dependency on the action before the handle method?

### ISSUE THREAD

**Issue by abishekrsrikaanth** [lorisleiva/laravel-actions#40]
Great work, love working with it. I recently came across this hurdle and I am not sure how to solve it. Is there a way to inject a dependency before the `handle` method is invoked? I added the `withValidator` method to the action and it requires an instance of `class` to perform validation. I went through the docs and I could find a way to inject a dependency that is accessible at the time of validation. Could you please let me know if it is possible and how to do it?

**Comment by abishekrsrikaanth** [comment]
nvm, I extended the class and added a constructor to inject dependencies on the constructor.

**Comment by lorisleiva** [comment]
Hi there, 👋

I’m sorry I’m not sure exactly what you are trying to achieve. However you shouldn’t really need to override the constructor for anything. There is even an `initialized` lifecycle hook that you can use.

If you want to inject stuff in the `withValidator` method or any other validation method, you can typehint them in the arguments of the method just like you would in the `handle` method.

I hope this helps. 🍀

**Comment by abishekrsrikaanth** [comment]
Thanks, the `initialized` hooks definitely helps. Appreciate the reply
