### ISSUE TITLE
Actions as Laravel Livewire Components

### ISSUE THREAD

**Issue by morrislaptop** [lorisleiva/laravel-actions#43]
Would you be open to this?

**Comment by lorisleiva** [comment]
Hi there 👋 

I did think about it when I originally started using Livewire but then I had a look into the codebase of a Livewire component it contains way too much logic to be compatible with an action.

They both contain their own way of storing attributes and whilst Laravel Action tries to be as non-intrusive as possible, Livewire has to be intrusive and opinionated to offer the set of features it offers.

Thus, it doesn't feel like merging the two whilst keeping the same feature set of both packages is possible.

However, I've been using both Livewire and Laravel Actions in my projects lately and it feels quite nice the way things are. Laravel Actions for domain logic, Livewire components as frontend components/presenters.

**Comment by abr4xas** [comment]
Hey @morrislaptop, I'm sorry for being almost 3 years later xD... 

I'm doing something like this:

```php
<?php

namespace {{ namespace }};

use App\Actions\Article\ManageArticlesAction;
use Illuminate\Validation\ValidationException;
use Livewire\Component;
use Livewire\ComponentConcerns\ValidatesInput;

class ManageArticles extends Component
{
   use ValidatesInput;

    public array $state = [
      'title' => '',
      'excerpt' => '',
      'body' => '',
    ];

    public function createContentForm()
    {
      $data = [
	'title' => $this->state['title'],
	'excerpt' => $this->state['excerpt'],
	'body' => $this->state['body'],
      ];

     $this->validate();

     ManageArticlesAction::run($data); // action
     
     $this->clearFields();
   }

   private function clearFields()
   {
     $this->state['title'] = '';
     $this->state['excerpt'] = '';
     $this->state['body'] = '';
   }
   
   public function updated($field): void
   {
     $this->validateOnly($field);
   }

   public function rules(): array
   {
     return ManageArticlesAction::make()->rules();
   }
}
```

:D
