### ISSUE TITLE
Consider using expectsJson instead of wantsJson when action runs as controller

### ISSUE THREAD

**Issue by jenky** [lorisleiva/laravel-actions#48]
https://laravelactions.com/actions-as-controllers.html#returning-http-responses

Since `wantsJson` only checks for `Accept` header but `expectsJson` does support ajax request and most likely clients expect JSON format on ajax request as well

**Comment by lorisleiva** [comment]
Hi there 👋 

To be honest, the difference between `wantsJson` and `expectsJson` confuses the hell out of me. 😅 

Are you suggesting we should maybe use both — `wantsJson || expectsJson` ?

**Comment by jenky** [comment]
I think we just need `expectsJson` since it uses `wantsJson` already. The exception handler also uses `expectsJson` to render the exception error either as html or json

<img width="909" alt="Screenshot 2020-07-17 at 14 22 20" src="https://user-images.githubusercontent.com/1808758/87759838-1c32be00-c839-11ea-8879-9d597fcfa5e4.png">

**Comment by lorisleiva** [comment]
Cool thanks for that. I'll leave that open until I have the chance to sort this out. In the meantime PRs are welcome. 🙂

**Comment by lorisleiva** [comment]
Released in [`v1.1.2`](https://github.com/lorisleiva/laravel-actions/releases/tag/v1.1.2). 🚀
