### ISSUE TITLE
Best practice - using constructor to pass typed objects or not?

### ISSUE THREAD

**Issue by rico** [lorisleiva/laravel-actions#50]
I really like the approach I can take with this package. Thank's for your work!

However, whenever possible, I would like to pass (typed) objects to my actions instead of an array of attributes. It just makes development - especially with the IDE - easier. I don't have to look into the action calls to know what is needed.

So, what is the suggested way to pass objects to the Action? Using a constructor with a docblock for the the run action - something like this:

```
/**
 * @method static run(Person $person)
 */
class PersonAction extends Action
{

    /**
     * @var Person
     */
    public $person;

    public function __construct(Person $person)
    {
        $this->person = $person;

        parent::__construct();
    }
    
    public function handle()
    {
        $person = $this->person;
        
        [...]

    }
}
```

? Or is there a better way?

**Comment by anyb1s** [comment]
I personally do
AddDamage::to($vehicle)->run($extradata);
where to() is a static constructor returns new AddDamage($vehicle); and can typehint the returned object.

**Comment by rico** [comment]
Interesting approach @anyb1s - thanks!

**Comment by rico** [comment]
What works pretty for for me is this:

```
/**
 * @method static run(Person $person)
 * @property Person person
 */
class PersonAction extends Action
{

    public function __construct(Person $person)
    {
        $this->person = $person;

        parent::__construct();
    }
    
    public function handle()
    {
        $person = $this->person;
        
        [...]

    }
}
```

The `$person` has a declaration, can be passed directly to the constructor when `run` as an object and gets resolved from the request when the action is used as controller.

**Comment by lorisleiva** [comment]
Hi Rico, 👋 

Unfortunately, overriding the constructor of an Action is comparable to overriding the constructor of Model. An Action needs to be able to be instantiated without any arguments because its attributes can be hydrated dynamically.

That being said you can achieve the same result as your example above using the `getAttributesFromConstructor` property.

```php
/**
 * @method static run(Person $person)
 * @property Person person
 */
class PersonAction extends Action
{
    protected $getAttributesFromConstructor = true;

    public function handle(Person $person)
    {
        // ...
    }
}
```

You can learn more about this in the documentation:

https://laravelactions.com/actions-as-objects.html#how-are-attributes-filled

**Comment by rico** [comment]
Hi @lorisleiva thanks for your response! I understand & makes sense :-)
