### ISSUE TITLE
Ignore `null` for command output

### ISSUE THREAD

**Issue by slashequip** [lorisleiva/laravel-actions#54]
When using an action as a command, the default behaviour, without the `consoleOutput` method, is to output the return value of the `handle` method.

In a lot of cases, at least in my uses, there is no return value and then the command just outputs `null` without formatting causing line inconsistencies, it'd be great if the output was ignored when `null`, as it's a nothing value anyway, and nothing output to the console.

**Comment by jstoks** [comment]
I have this little PR #67. I thought it would be a quick one, but it's not obvious how to test this.

With the tools available in Laravel, I'm not sure how to test this case. There is no `expectsNoOutput`. I looked at the framework source and I just don't see a good option for implementing it.

Any ideas?

**Comment by lorisleiva** [comment]
Fixed by #67 and released as `v1.1.7`. 🚀
