### ISSUE TITLE
Job serialization for models

### ISSUE THREAD

**Issue by slashequip** [lorisleiva/laravel-actions#55]
When queuing an action as a job the actions data is not serialized like we would see by default in a Laravel job, I believe this is due to `attributes` being an array and Laravel's `SerializesModels` trait only looks at the top level property and not at the values of an array.

To achieve this I believe we could loop through the attributes array during the Laravel Actions `SerializesModels` `__sleep` method and apply the same logic Laravel does for each of those properties, same applies for the`__wakeup` method to, for rehydrating this data.

**Comment by yamenarahman** [comment]
I'm facing this issue too.
While dealing with action as an object works great, when I tried to dispatch it as a job it couldn't realize any of attributes. So I had refactor the actions to normal jobs.

**Comment by lorisleiva** [comment]
Thanks Sam! Let's fix this when we have a moment to pair 💪 ❤️

**Comment by jstoks** [comment]
I briefly took a look at this, but I'm unsure on how to proceed. Any insights on the best way to fix this?

**Comment by lorisleiva** [comment]
Released in `v1.2.0`. 🚀
