### ISSUE TITLE
Annotation request

### ISSUE THREAD

**Issue by lorisleiva** [lorisleiva/laravel-actions#6]
This request from @deviouspk started in another issue. In order to not lose focus on the original issue, I'm moving the discussion here. Here is the description of the feature request:

---

What i would love though as extra feature would be something like this. This can be accomplished with doctrine/annotations (which is present in laravel by default if i'm not mistaken). Tell me what you think ;)

![image](https://user-images.githubusercontent.com/7100315/58661548-6ea8d680-8328-11e9-8eb6-d4989dce619a.png)

![image](https://user-images.githubusercontent.com/7100315/58662477-94cf7600-832a-11e9-9633-3c07668d2d93.png)

Not the best example :p but you get the point. The rules are generated from the attributes. And you have the flexibility to typehint the necessary properties on the class. It will also work great with actions that are used as listeners.

_Originally posted by @deviouspk in https://github.com/lorisleiva/laravel-actions/issues/3#issuecomment-497471425_

**Comment by lorisleiva** [comment]
Honestly, I'm not a big fan of annotations in general but that's a personal preference. I'm going to leave that issue for a bit to see if it's a popular demand.

In the meantime, feel free to document your request in more detail.

**Comment by deviouspk** [comment]
Hmm well there's decent ide support for annotations, it's clean  +how else would you want to link an attribute class with a property? I'm open for suggestions

**Comment by xtrasmal** [comment]
@deviouspk 

Annotations are first class citizens in PHP, but they have there place.
For your info and anybody who sees this and is interested in how the AnnotationRegistry can be used to register custom Annotations

```php
<?php namespace App\Providers;

use Illuminate\Support\ServiceProvider;
use Doctrine\Common\Annotations\AnnotationRegistry;

class AnnotationProvider extends ServiceProvider
{

	public function boot()
	{

		AnnotationRegistry::registerLoader(function ($class) {
			$namespace = 'App\Annotations\\';
			$check = strtolower(substr($class, 0, strlen($namespace))) 
					
			if ($check === strtolower($namespace)) {
				$loaded = class_exists($class);

				return $loaded;
			}

			return false;
		});

	}
}

```

Then create your annotation

```php

<?php namespace App\Annotations;

/** @Annotation */
class Pincode
{
    /**
     * @var string
     */
    public $attribute;

    /**
     * @return string
     */
    public function getAttribute()
    {
        return $this->attribute;
    }
}

```

Then you could do something like:

```php

use Doctrine\Common\Annotations\AnnotationReader;

class UpdatePincode extends Action
{
    /**
     * @Pincode
     */
	public $pincode;

	private function validate()
	{
		// invoke some runtime stuff
	}
}

```

validate could be something that grabs reflection params

```php

$annotationReader = new AnnotationReader();

$reflectionProperty = new ReflectionProperty('UpdatePincode', 'pincode');
$propertyAnnotations = $annotationReader->getPropertyAnnotations($reflectionProperty);

```

I wouldn't go the annotation way for this library, because it is too vague. I'd probably do something like this on Action creation:

```php

class UpdatePincode extends ActionThatDoesNotExtendController
{
    /**
     * @var Pincode $pincode
     */
	private $pincode;
	
	public function __construct(Pincode $pincode)
	{
		$this->pindcode = $pincode;
	}
}

```

Maybe just use a self executing command, decorated with a command validator, a command bus. Call it Action, and create another, call it Reaction. etc etc

Ah well. Good luck to y'all.

**Comment by lorisleiva** [comment]
@xtrasmal Hi there, thanks for your input. I hope this helps anyone looking to use annotations in their Laravel projects.

On the other hand, I've got no plans to add annotations to Laravel Actions for now so I'm going to close this issue.
