### ISSUE TITLE
[Advice] Different `handle()` method arguments in create/update actions

### ISSUE THREAD

**Issue by xphoenyx** [lorisleiva/laravel-actions#62]
Hey!

Opening a new issue as @lorisleiva adviced in #46 because still struggling to find an answer.

The case: I have two action classes - `CreateApplication` and `UpdateApplication`. They both have identical `rules()` and `messages()` methods, but the latter class has typed `$application` argument in `handle()` method, while the former has the same method with no arguments at all. What would be the best way to implement these actions so they share the same rules, but have different amount of arguments in `handle()` method?

I have few options how this problem can be solved, like moving repeating logic into a trait or instantiating one action class in another and use its logic, but they seem more like an overkill or "bad-practices" options for me. I also don't really like the idea of overriding `authorize()` method as was suggested in the mentioned issue because it can also have a different number of arguments in both actions.

Thanks in advance for an advice! 😃

**Comment by lorisleiva** [comment]
Hi there 👋 

It seems like method arguments are what's blocking you from merging these two actions together. However, these arguments are simply resolved from the `$attributes` property anyway. So you could merge them by not providing any arguments to `handle` (or any other Laravel Actions methods) like so:

```php
class UpdateOrCreateApplication extends Action
{
    public function rules()
    {
        return [...];
    }

    public function handle()
    {
        if ($this->application) {
            $this->application->update($this->validated());
        } else {
            $this->application = Application::create($this->validated());
        }

        // Some common logic...
    }
}
```

I hope this helps, otherwise feel free to provide some code so I can take a closer look. 🙂

**Comment by xphoenyx** [comment]
> It seems like method arguments are what's blocking you from merging these two actions together

That's right. The perfect solution could be also an inheritance of `CreateApplication` class, as there might be also an action-specific logic in both classes. Anyways, big thank you for the hint - action's dynamic properties might indeed do the trick.
I think the issue can be closed for now.

Cheers!
