### ISSUE TITLE
[2.0] Inherit auth policy method response message by default

### ISSUE THREAD

**Issue by jalt007** [lorisleiva/laravel-actions#71]
Hey this package is great!

For https://laravelactions.com/authorisation.html, I've noticed custom [policy response messages](https://laravel.com/docs/8.x/authorization#policy-responses) are not inherited e.g. `Response::deny('custom denied message')`.

I had a quick look into this & it seemed like to get them to be inherited by default would introduce a breaking change by introducing an extra parameter to `failedAuthorization()`.

Is this something that could be considered for V2?

**Comment by lorisleiva** [comment]
Hi there 👋 

That's a very good point. Thanks for raising this.

I will make we this is supported by v2 since it would indeed be a breaking change for v1.

**Comment by lorisleiva** [comment]
This has been implemented in v2. It's not going to be release for a little while yet but it's ready. 🙂 

https://github.com/lorisleiva/laravel-actions/blob/696ceed49431127238425803f50f7ce3d68de54f/tests/AsControllerWithPolicyResponsesTest.php

**Comment by jalt007** [comment]
Nice one thanks! Looking forward to it.
