### ISSUE TITLE
 An alias (serializeFromBaseSerializesModels) does not exist

### ISSUE THREAD

**Issue by andrewskm** [lorisleiva/laravel-actions#74]
When using versions 1.2 and higher on Laravel 5.8, I am getting the error
` An alias (serializeFromBaseSerializesModels) was defined for method __serialize(), but this method does not exist` in the file src/Concerns/SerializesModels.php line 7.

I was however able to get things to work by using 1.1.8.
I looked over the docs to make sure I had what was needed, so not too sure if the Laravel version is outdated for 1.2 and higher or just an error with the package.

**Comment by lorisleiva** [comment]
Ha sorry I did not realise this method was not provided in 5.8. I should have removed support for 5.8 on version 1.2 to avoid this error.

You will need to explicitly set the version `1.1` on your `composer.json` using the following format: `1.1.*`.

**Comment by andrewskm** [comment]
No worries, that is exactly what I did to get it working for me.
Thanks for the clarification!
