### ISSUE TITLE
Additional method for creation

### ISSUE THREAD

**Issue by Wulfheart** [lorisleiva/laravel-actions#75]
When creating an action I'd like to use the autocompletion of my IDE. However, when using an array I can't use the autocompletion. Any plans to update it?

Im thinking of something similar to a build method.

````php
$action = PublishANewArticle::build(title: 'My blog post', body: 'Lorem ipsum.');

````

**Comment by lorisleiva** [comment]
Laravel Actions v2 is what you're looking for. I'm hoping to release it either today or tomorrow. Just finishing up the documentation. It's 95% done, you can [have a look at it here](https://deploy-preview-7--laravel-actions.netlify.app/) in the meantime. 🙂

**Comment by Wulfheart** [comment]
This looks awesome!
