### ISSUE TITLE
User update validation rules problem

### ISSUE THREAD

**Issue by hcivelek** [lorisleiva/laravel-actions#76]
He, what I'll mention is not an "issue" I must say. If the message not proper just delete it. When I want to update a user with LaravelActions, I want to use some classic validation rules like email and username that must be unique except for the user's own email and username. But model binding not there while in rules() function. If I use middleware to get the user before validation then I have two same DB queries. What should I do?

**Comment by cyrillkalita** [comment]
@hcivelek how did you solve it>
