### ISSUE TITLE
Method ReflectionParameter::getClass() is deprecated

### ISSUE THREAD

**Issue by hcivelek** [lorisleiva/laravel-actions#79]
Hello,

I received the "Method ReflectionParameter::getClass() is deprecated" error while working PHP 8.

I'm not sure about what I supposed to do. The answer described here: https://php.watch/versions/8.0/deprecated-reflectionparameter-methods#:~:text=Deprecated%3A%20Function%20ReflectionParameter%3A%3AgetClass,are%20in%20a%20single%20Union.

**Comment by lorisleiva** [comment]
Hi there 👋 

Are you sure you're using the latest version? Support for 8.0 was added on the latest release.

**Comment by hcivelek** [comment]
You're right. Sorry about that.

**Comment by lorisleiva** [comment]
No worries 🙂
