### ISSUE TITLE
[Command] make:action directory/filename

### ISSUE THREAD

**Issue by exodusanto** [lorisleiva/laravel-actions#8]
Hi 👋🏻
Thank you for your amazing work on this repo 🤙🏻

I notice that the command `make:action (name)` support only the filename and there isn't a way to pass also the namespace.

Example:
```bash
php artisan make:action User\UserProfile
```

Result -> App\Actions\UserUserProfile

Is there a way to implement this functionality? 😀

**Comment by lorisleiva** [comment]
Hi there 👋 

Thanks, I'm glad you like it!

In order to do this, you need to use forward slashes instead of backslashes.

```sh
php artisan make:action User/UserProfile
```

I hope this helps. 🍀

**Comment by exodusanto** [comment]
Ops 😬
Yes... all artisan make commands use that slash.

Thank you 😅
