### ISSUE TITLE
Add scaffold command

### ISSUE THREAD

**Issue by Wulfheart** [lorisleiva/laravel-actions#85]
Something like ``php artisan make:action name``. It still needs to be clarified which skeleton will be used. I'd like to contribute this command.

**Comment by morrislaptop** [comment]
Also up for this feature! The user should be able to customise their boilerplate by publishing the stub into their app?

**Comment by Wulfheart** [comment]
> I also want users to feel encouraged to first write their action without any constraints and I'm worried that added a `make` command might make them feel like this is "the" way of using the package if you know what I mean.

I understand your concerns. However, scaffolding commands are the most common way in the laravel ecosystem to scaffold code and I'm using Laravel Actions in 5 different editors/environments so it quickly becomes tedious to add a template everywhere.

![](https://media1.giphy.com/media/Ld77zD3fF3Run8olIt/giphy.gif)

**Comment by lorisleiva** [comment]
Well how can I argue with this GIF haha. Sorry about the delay, I'm crazy busy with a sideproject feature at the moment. I should have more time in a week or two for OSS.

I've merged that PR and released it as `v2.0.7`. 🚀

**Comment by Wulfheart** [comment]
The node manager feature for octohook looks amazing.
