### ISSUE TITLE
Non static method 'registerRoutes' should not be called statically.

### ISSUE THREAD

**Issue by FrancisMawn** [lorisleiva/laravel-actions#89]
Hi,

I came across this issue, not a big deal but I thought I should mention it to you. When using the Actions facade, vscode is complaining that the `registerRoutes` method should not be called statically. I think this is due to the fact that your facade doc doesn't include the static word. Based on how Laravel does their facades, I think it should be written this way:

`@method static void registerRoutes($paths = 'app/Actions')`

Adding the static word removed the intelephense warning. 

Cheers

**Comment by lorisleiva** [comment]
Hi there 👋 

This has been fixed and released as [`v2.1.1`](https://github.com/lorisleiva/laravel-actions/releases/tag/v2.1.1). 🚀 

Thanks for raising this! 🍺
