### ISSUE TITLE
Events are not fired

### ISSUE THREAD

**Issue by znsstudio** [lorisleiva/laravel-actions#9]
I installed this package, and my listeners stopped working. After removal of package everything returned back normal.

**Comment by cbaconnier** [comment]
It has been discussed here: https://github.com/lorisleiva/laravel-actions/issues/7
It's almost resolved

**Comment by lorisleiva** [comment]
Thanks @cbaconnier for the detailed summary. 👍 

I will release this fix ASAP but yeah in the meantime you have to use the `dev-lab/decorate_event_dispatcher` release.

@znsstudio If you could try that release and let me know if it fixes your issue (just to be sure) that would be much appreciated. 🙏

**Comment by lorisleiva** [comment]
Fixed by #11.

Please reopen if the problem persists.
