### ISSUE TITLE
Bug: Too few arguments to function Lorisleiva\Actions\ActionRequest::Illuminate\Foundation\Providers\{closure}(), 0 passed in

### ISSUE THREAD

**Issue by sawirricardo** [lorisleiva/laravel-actions#96]
Too few arguments to function Lorisleiva\Actions\ActionRequest::Illuminate\Foundation\Providers\{closure}(), 0 passed in /Users/ricardosawir/Documents/Personal/php/20210312-peoplebond/vendor/laravel/framework/src/Illuminate/Macroable/Traits/Macroable.php on line 114 and exactly 1 expected

```
 public function asController(ActionRequest $actionRequest)
    {
        $actionRequest->validate(); // <-- somewhere the error relates here
        $validatedData =  $actionRequest->validated();
        $this->handle($validatedData);
        return redirect()->route('verification.notice');
    }
```

Laravel: 8.32.1
Laravel Action: 2.x

**Comment by lorisleiva** [comment]
Hi there 👋 

Just having a quick look at your code and you actually don't need to run `validate` on the request. If you typehint the request using `ActionRequest`, it will automatically validate the data for you just like a `FormRequest` would.

It might not have anything to do with the bug though. Let me know if that helps. 🙂

**Comment by sawirricardo** [comment]
Ah okay, so I just need to run the "validated" func to get the data?

I'll give it a try tomorrow, there are other issues related with verifying email. Always redirected to login route. I'll let you know about this.

**Comment by sawirricardo** [comment]
Hi, tested it and it works just like you described. Thank you @lorisleiva
