### ISSUE TITLE
Chain jobs with the following depending on the return of the previous job?

### ISSUE THREAD

**Issue by andruu** [lorisleiva/laravel-actions#98]
Looking for something similar to https://github.com/adomokos/light-service where you can run a chain of jobs but the children rely on a context or the return of the previous. Is this possible?

**Comment by lorisleiva** [comment]
Hi there 👋 

Laravel Actions is not providing anything extra when it comes to job features or more specifically job chaining. This package wraps plain PHP classes into decorators that act as various framework patterns such as Jobs. Therefore, everything you can do with Laravel Actions, you can do with Laravel.

To answer your question, I would recommend reading the [documentation on Job chaining](https://laravel.com/docs/8.x/queues#job-chaining), but if I remember correctly chained jobs do not share their data.

You might want to use a custom approach by dispatching the next job directly inside the previous job. Alternatively, you might also benefit from an implementation that relies on the [`Pipeline` component from Laravel](https://github.com/laravel/framework/tree/8.x/src/Illuminate/Pipeline) — the same that is used for middleware chaining.

That's all I've got for you haha. I hope this helps. Good luck. 🍀
